'use client';
import {useEffect,useState} from 'react';
const projects=[
{name:'NexusCode',type:'AI developer platform',accent:'violet',summary:'A collaborative software workspace combining project management, an in-browser Monaco editor, real-time collaboration, and AI-assisted code generation and bug detection.',stack:['React 19','FastAPI','PostgreSQL','WebSockets','Gemini API','Docker'],repo:'https://github.com/govindturkar69-crypto/NexusCode',live:'https://nexus-code-chi.vercel.app',detail:'Built as a final-year project with JWT authentication, GitHub OAuth, a containerized backend, and separate Vercel and Render deployments.'},
{name:'TalentAI',type:'AI recruitment platform',accent:'blue',summary:'A two-sided hiring platform that parses resumes, extracts skills, scores job fit, and ranks candidates for recruiter review.',stack:['Python','Flask','MySQL','scikit-learn','Plotly'],repo:'https://github.com/govindturkar69-crypto/TalentAI-Recruitment-Platform',live:'https://talentai-recruitment-platform.onrender.com',detail:'Combines weighted skill matching with TF-IDF cosine similarity, plus candidate workflows, recruiter analytics, notifications, and Excel export.'},
{name:'RealtyIQ',type:'Full-stack ML product',accent:'amber',summary:'An end-to-end real-estate price prediction experience for Indian markets, including confidence ranges, explainability, listings, trends, and comparison tools.',stack:['Next.js 14','FastAPI','XGBoost','SHAP','Express','MongoDB'],repo:'https://github.com/govindturkar69-crypto/RealtyIQ',live:'https://realty-iq-puce.vercel.app',detail:'Turns a real Kaggle housing dataset into an authenticated product spanning model serving, APIs, dashboards, and model explainability.'},
{name:'Aurora Weather',type:'Resilient full-stack app',accent:'cyan',summary:'Live weather with real provider data, automatic fallback, Redis cache-aside, air quality, pollen, rain nowcasting, and a weather-reactive interface.',stack:['React','Node.js','TypeScript','Redis','Docker'],repo:'https://github.com/govindturkar69-crypto/aurora-weather',live:'https://aurora-weather-six.vercel.app',detail:'Built during the KodeKalp internship. A typed Express API normalizes Tomorrow.io and Open-Meteo while the frontend remains provider-agnostic.'},
{name:'VeriDoc',type:'Grounded RAG assistant',accent:'green',summary:'A retrieval-augmented assistant designed to answer questions over institutional documents with citations instead of unsupported responses.',stack:['Python','RAG','LLMs'],repo:'https://github.com/govindturkar69-crypto/VeriDoc',detail:'A final-year project focused on grounded information retrieval and citation-backed answers.'},
{name:'LSTM Stock Predictor',type:'Honest ML evaluation',accent:'rose',summary:'A PyTorch forecasting dashboard that avoids flattering price-level metrics and evaluates returns and direction with walk-forward validation.',stack:['PyTorch','Streamlit','pandas','Plotly','yfinance'],repo:'https://github.com/govindturkar69-crypto/stock-price-lstm',live:'https://stock-price-lstm-eaqfzb6hbgmjdf9el5thnh.streamlit.app/',detail:'Uses leakage-safe, scale-free features and reports the honest result: daily returns show little reliable signal, while volatility is more learnable.'}];
const skills=[['Languages',['JavaScript','TypeScript','Python']],['Product engineering',['React','Next.js 14','Vite','Tailwind CSS','Node.js','Express','FastAPI']],['Data & AI',['PyTorch','scikit-learn','XGBoost','RAG','Gemini API']],['Systems',['MongoDB','PostgreSQL','Redis','Docker','WebSockets','REST APIs']],['Delivery',['Git','GitHub','Vercel','Render','JWT Auth']]];
const Arrow=()=> <span aria-hidden="true">↗</span>;
export default function Home(){
 const[open,setOpen]=useState<string|null>(null);const[menu,setMenu]=useState(false);
 useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('seen')),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));return()=>io.disconnect()},[]);
 return <><a className="skip" href="#main">Skip to content</a><header className="nav-wrap"><nav className="nav shell" aria-label="Primary navigation"><a href="#top" className="brand"><span>GT</span> Govind Turkar</a><button className="menu-btn" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'}</button><div className={'navlinks '+(menu?'open':'')} onClick={()=>setMenu(false)}><a href="#work">Work</a><a href="#experience">Experience</a><a href="#about">About</a><a className="nav-cta" href="mailto:govindturkar69@gmail.com">Let’s talk <Arrow/></a></div></nav></header>
 <main id="main"><section id="top" className="hero shell"><div className="hero-grid"/><div className="glow g1"/><div className="glow g2"/><div className="hero-copy"><p className="eyebrow hero-in"><span className="status-dot"/> Open to internships & full-time roles</p><h1 className="hero-in delay-1">I build intelligent products,<br/><em>end to end.</em></h1><p className="lede hero-in delay-2">I’m Govind, a full-stack developer and final-year CSE student turning applied AI into reliable, usable software—from model and API design to polished production interfaces.</p><div className="hero-actions hero-in delay-3"><a className="button primary" href="#work">Explore selected work <span>↓</span></a><a className="button ghost" href="/Govind_Turkar_Resume.docx" download>Download résumé</a></div><div className="hero-meta hero-in delay-3"><span>Nagpur, India</span><span>Full Stack Developer Intern · KodeKalp</span></div></div>
 <div className="hero-visual hero-in delay-2" aria-label="Product engineering workflow"><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="core"><small>BUILD LOOP</small><strong>01 → 04</strong><span>Discover · Design<br/>Engineer · Ship</span></div><div className="chip c1"><b>AI</b><span>Applied intelligence</span></div><div className="chip c2"><b>FE</b><span>Product interfaces</span></div><div className="chip c3"><b>BE</b><span>APIs & systems</span></div></div></section>
 <section className="signal shell reveal"><p>Working across the complete product stack</p><div><span>12</span> public repositories</div><div><span>2023—27</span> B.Tech CSE</div><div><span>2026—Now</span> Industry experience</div></section>
 <section id="work" className="section shell"><div className="section-head reveal"><div><p className="kicker">Selected work / 01</p><h2>Products with<br/>technical substance.</h2></div><p>A focused selection spanning collaborative developer tooling, applied machine learning, resilient APIs, and grounded AI.</p></div><div className="projects">{projects.map((p,i)=><article key={p.name} className="project reveal"><div className={'project-art '+p.accent}><span className="art-index">0{i+1}</span><div className="mini-window"><i/><i/><i/><b>{p.type}</b><strong>{p.name.slice(0,2).toUpperCase()}</strong></div></div><div className="project-body"><div className="project-top"><p>{p.type}</p><span>0{i+1}</span></div><h3>{p.name}</h3><p className="summary">{p.summary}</p><ul className="tags">{p.stack.map(s=><li key={s}>{s}</li>)}</ul><div className="project-actions"><button aria-expanded={open===p.name} onClick={()=>setOpen(open===p.name?null:p.name)}>{open===p.name?'Hide details':'View case notes'} <span>+</span></button><a href={p.repo} target="_blank" rel="noreferrer">Code <Arrow/></a>{p.live&&<a href={p.live} target="_blank" rel="noreferrer">Live <Arrow/></a>}</div><div className={'case-note '+(open===p.name?'open':'')}><p><b>Inside the build.</b> {p.detail}</p></div></div></article>)}</div></section>
 <section id="experience" className="section alt"><div className="shell"><div className="section-head reveal"><div><p className="kicker">Experience / 02</p><h2>Learning by<br/>shipping.</h2></div><p>Professional experience grounded in building and deploying full-stack features within a remote engineering team.</p></div><article className="experience reveal"><div className="exp-date">Jun 2026 — Present</div><div><p className="role">Full Stack Developer Intern</p><h3>KodeKalp Global Technologies</h3><p>Developing and shipping full-stack features as part of a remote engineering team. Built Aurora Weather: a live weather product with forecasts, air quality, moon phases, a TypeScript API, Redis caching, and multi-provider resilience.</p><div className="exp-stack">React + Vite · Node/Express · TypeScript · Redis · Vercel · Render · Upstash</div></div><span className="remote">Remote</span></article></div></section>
 <section id="about" className="section shell"><div className="about-grid"><div className="reveal"><p className="kicker">Profile / 03</p><h2>Engineering the bridge between AI and useful software.</h2></div><div className="about-copy reveal"><p>My work sits where applied AI meets product engineering. I enjoy translating an idea into the complete system around it: data flow, model or retrieval layer, APIs, authentication, persistence, interface, and deployment.</p><p>That range lets me reason beyond a single layer. Whether it’s citation-grounded RAG, explainable price prediction, or a resilient weather API, I care about the quality of the system and the experience around it.</p><a href="mailto:govindturkar69@gmail.com">Start a conversation <Arrow/></a></div></div><div className="skill-grid">{skills.map(([title,items],i)=><div className="skill-card reveal" key={title as string}><span>0{i+1}</span><h3>{title as string}</h3><div>{(items as string[]).map(x=><small key={x}>{x}</small>)}</div></div>)}</div></section>
 <section className="section alt"><div className="shell education"><div className="reveal"><p className="kicker">Education / 04</p><h2>Computer science,<br/>in progress.</h2></div><div className="edu-list reveal"><article><span>2023—2027</span><div><h3>B.Tech, Computer Science & Engineering</h3><p>G H Raisoni College of Engineering, Nagpur · Final year, ongoing</p></div></article><article><span>2023</span><div><h3>Senior Secondary (XII), Science</h3><p>Sukanya Sankalp Niketan HSC, Kati · 68%</p></div></article><article><span>2021</span><div><h3>Secondary (X)</h3><p>Sukanya Sankalp Niketan High School, Kati · 86.4%</p></div></article></div></div></section>
 <section className="contact shell reveal"><p className="kicker">Contact / 05</p><h2>Have a hard problem<br/>worth building?</h2><p>I’m open to internships, full-time opportunities, and thoughtful collaborations across full-stack and applied AI engineering.</p><div><a className="button primary" href="mailto:govindturkar69@gmail.com">Email Govind <Arrow/></a><a className="button ghost" href="https://github.com/govindturkar69-crypto" target="_blank" rel="noreferrer">GitHub profile <Arrow/></a></div></section></main>
 <footer><div className="shell"><span>© 2026 Govind Turkar</span><span>Designed around real work, not vanity metrics.</span><a href="#top">Back to top ↑</a></div></footer></>
}
